server:
  port: 9001

  ssl:
    certificate: ${SSL.CERTIFICATE}
    certificate-private-key: ${SSL.CERTIFICATE.PRIVATE.KEY}

spring:
  application:
    name: order-service

api:
  product:
    base-url: ${PRODUCT.BASE_URL}
    get-product: ${PRODUCT.GET_PRODUCT}